<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>18fbd9d1-2204-4828-9b7a-77f20eba9eb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/section/main/div/div[3]/div/table/tbody/tr/td[7]/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.editIcon > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6efd1bcd-2466-4634-adbf-04278ec3ade9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/edit.adc1cd27.png</value>
      <webElementGuid>1c94d7b3-048a-4d89-8886-1abeccff8bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5989a6f3-f014-4f25-907f-be09ab2efc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>32c61aa3-f945-4529-b94d-49e228936fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a9c4b4f8-75cb-4d72-a49e-e89dbe653496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>229345e0-93e3-471b-8fe0-5c5698d1b4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>78d5e554-484d-403c-8653-a19a031b2e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;body-container col-lg-10 col-md-10 col-sm-7&quot;]/div[@class=&quot;table-wrapper retrospective-table&quot;]/div[1]/table[@class=&quot;table table-sm table-striped table-bordered table-hover&quot;]/tbody[1]/tr[1]/td[@class=&quot;edit&quot;]/span[@class=&quot;name-text&quot;]/a[@class=&quot;editIcon&quot;]/img[1]</value>
      <webElementGuid>3ee06eab-dfd3-49d2-9ed2-711afa9c5b54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/section/main/div/div[3]/div/table/tbody/tr/td[7]/span/a/img</value>
      <webElementGuid>6bd7ab26-23f5-42e2-bee5-79417114f09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>0101dd98-8b01-44c2-b73d-fa895eb363ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/static/media/edit.adc1cd27.png']</value>
      <webElementGuid>4fc163af-48b7-4c88-bc05-f66dd0ae63d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
