<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please add the number of times for th_a363bd</name>
   <tag></tag>
   <elementGuidId>c0757661-536a-439d-99a4-a1b9d4f24bc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frequencyDuration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frequencyDuration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f1d74dc-6552-4e20-951f-604360164273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a5dfd28d-d113-4f7d-b2d6-f77bf74ef5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please add the number of times for the reminder</value>
      <webElementGuid>1f10acd6-2d7e-4dbe-8391-2ea4d76f645d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9291118f-82ed-4b0b-9ca4-9870f0c769a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frequencyDuration</value>
      <webElementGuid>08d16143-c55f-4615-a104-1ad2bf810c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>96a6dbdd-5558-4c2e-ba0d-6078468ad9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success</value>
      <webElementGuid>53bf6110-6e9f-4b54-871c-ee0a09eb2f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frequencyDuration&quot;)</value>
      <webElementGuid>c6598440-cd65-4a96-a22e-ade99018eb0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frequencyDuration']</value>
      <webElementGuid>b7a87c4b-ba63-44c3-8652-471b4328dbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/section/main/div/div/div/div/div/div[2]/div[2]/form/div[11]/div/div[2]/div/div/input</value>
      <webElementGuid>d0517704-5f16-4f64-9dcb-3d9edcc8fe9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/div/div/input</value>
      <webElementGuid>b880a97c-fa61-458d-96ad-ac9cebf1a3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Please add the number of times for the reminder' and @id = 'frequencyDuration']</value>
      <webElementGuid>b9cdea62-cd0e-42de-b45a-ee9213cae4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
