<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>d6ec9881-d39d-4fbb-93fc-a3c7730d884c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9166c11-5a09-4964-91b3-62e203f7fad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e64ba188-48f8-43ab-869d-07565c7fd402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password (8 characters)</value>
      <webElementGuid>3b10d584-eed6-46f0-8dec-903b3978a56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3f19fb0b-6963-4cba-98a9-da5122fdcfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>b2c6ab8a-57e8-44c6-bb74-b633a8dac386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login-page container-fluid&quot;]/div[@class=&quot;login-row row&quot;]/div[@class=&quot;login col-md-6 offset-md-3&quot;]/div[@class=&quot;login-wrapper&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;mb-3 input-wrapper password-input&quot;]/div[@class=&quot;text-input&quot;]/input[@class=&quot;undefined&quot;]</value>
      <webElementGuid>6d9b6aa7-27f8-4c50-9c21-5909b363247e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7a6c053-3c7f-4ec0-96de-d10723144071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3e9fd497-3bc9-4316-b135-33b33713d5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password (8 characters)</value>
      <webElementGuid>9daaa1a5-539f-413a-8e34-2d8b4f1cf9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2189146e-3101-44c5-a5ce-1077ffb4bb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>f81fc330-5193-4062-a584-1201fc24e235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login-page container-fluid&quot;]/div[@class=&quot;login-row row&quot;]/div[@class=&quot;login col-md-6 offset-md-3&quot;]/div[@class=&quot;login-wrapper&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;mb-3 input-wrapper password-input&quot;]/div[@class=&quot;text-input&quot;]/input[@class=&quot;undefined&quot;]</value>
      <webElementGuid>ef7a3c9e-3713-4031-bddc-d52bfa8b38f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>424a2c8b-8887-4d02-8e59-98e2e88e5585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>964dd89f-6f36-4eb4-afae-392e31fd850d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1ae103ac-daf3-4c82-885c-09427f92a830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter your password (8 characters)' and @name = 'password']</value>
      <webElementGuid>ca6549f0-13e2-4b30-a137-b949b34c95da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
