<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>1d262292-0172-42fc-9bb0-754a1527a600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.full-width-btn.btn.btn-primary.btn-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ac521b2-a743-4e33-aac8-a548cd4142ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f0327c9-95c9-4cac-a32b-484880a8e4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width-btn btn btn-primary btn-lg</value>
      <webElementGuid>b9656dc2-ce56-4b81-b07c-ec9b82906981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>40674cfa-32de-4732-8564-3d28944d625f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login-page container-fluid&quot;]/div[@class=&quot;login-row row&quot;]/div[@class=&quot;login col-md-6 offset-md-3&quot;]/div[@class=&quot;login-wrapper&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;submit-wrapper&quot;]/button[@class=&quot;full-width-btn btn btn-primary btn-lg&quot;]</value>
      <webElementGuid>a051bac1-7beb-4895-9f8f-91f2ec00d37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8b3f00c-056f-4416-a92f-658842908e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72847cef-1697-4e65-9515-15cdd0bfc662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width-btn btn btn-primary btn-lg</value>
      <webElementGuid>589ba593-e5a3-433f-a5a3-c2879bc5ace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>48c1b6b5-b007-4df2-8fe2-85324c7f60de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login-page container-fluid&quot;]/div[@class=&quot;login-row row&quot;]/div[@class=&quot;login col-md-6 offset-md-3&quot;]/div[@class=&quot;login-wrapper&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;submit-wrapper&quot;]/button[@class=&quot;full-width-btn btn btn-primary btn-lg&quot;]</value>
      <webElementGuid>0a656bf4-a032-4f8a-907f-3a60a79bfe4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>c449e27e-bc77-4ffa-8139-0119044a6eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/form/div[3]/button</value>
      <webElementGuid>94544ba2-ae25-4f79-9f96-dcc7fa175495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>87c15531-b302-4851-958b-c7461ac69ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>b140b411-a54c-43bf-9b4f-18a767338719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>27126f73-0602-4d3a-9b55-e86147e10d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>62d488d2-16de-4a08-814b-860f6515dd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>2e4a85f4-5d98-4489-a20e-97c44b62ace7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
