<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_sad</name>
   <tag></tag>
   <elementGuidId>f800d001-f522-4cfc-ab4a-809a365f3d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.ant-layout-header.main-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/section/header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>de5fec9c-0507-4db3-a2b9-d63daa7e3b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-layout-header main-header</value>
      <webElementGuid>37fea481-6631-44d2-9427-6b6e401df453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sad</value>
      <webElementGuid>164cece3-1e3e-4529-bc8d-7b0cb41158a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/header[@class=&quot;ant-layout-header main-header&quot;]</value>
      <webElementGuid>31b08676-83a8-43ee-91cb-8d4e0660c77b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/section/header</value>
      <webElementGuid>df003374-3795-4dc9-a5ae-7ade5fe84568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::header[1]</value>
      <webElementGuid>8d76c224-6df9-4bc6-9d22-b610c27e01e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/following::header[1]</value>
      <webElementGuid>fb37727f-b82f-4227-bc82-85915b627d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Organization (*)'])[1]/preceding::header[1]</value>
      <webElementGuid>4707312a-739b-4527-bfa6-f8a742b26535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>a7ffd1a0-cb4b-408e-affc-4af2f8de42a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = 'sad' or . = 'sad')]</value>
      <webElementGuid>ed9181a4-5e34-44d5-a9f3-d77fa1c3129f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
